### ISSUE TITLE
Pull Request required to complete Readme

### ISSUE THREAD

**Issue by jblair87** [learn-co-curriculum/javascript-map#10]
(Refer #8 ) Lesson requires pull request to complete. I believe the master branch and the branch created to fix this issue ("change-to-readme" branch) have not been merged.

**Comment by gj** [comment]
Hi @jblair87 !

That branch was merged in about 7 months ago: https://github.com/learn-co-curriculum/javascript-map/pull/7

Flipped it to a README on our end; should be all fixed now!
