### ISSUE TITLE
No actual tests in test file

### ISSUE THREAD

**Issue by Saturn226** [learn-co-curriculum/javascript-map#5]
There seems to be some arbitrary test within the index-test.js that isnt really testing for anything and also throws a syntax error.  If you change line 16 to say

  expect(true).toBe(true) it will allow the test to pass so that the lesson can be submitted.

**Comment by cassaram09** [comment]
Want to bump this issue - encountered a student today who was having trouble passing the lab because of this, even this his code was correct. I used Ashley's above solution.

@aturkewi

**Comment by aturkewi** [comment]
I just `rm -rf`ed the whole `test/` dir and changed it from a lab to a readme. Thanks for pointing out this issue!
